# Generated by Django 2.0.3 on 2020-08-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('pricetype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('pricetypeName', models.CharField(blank=True, max_length=15, null=True, verbose_name='生猪产品类型')),
                ('description', models.CharField(blank=True, max_length=32, null=True, verbose_name='描述')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '价格类型',
                'verbose_name_plural': '价格类型',
                'db_table': 'egg_pricetype',
            },
        ),
    ]
