# Generated by Django 2.0.3 on 2020-08-26 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0002_pricetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPriceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('dailyprice', models.FloatField(blank=True, null=True, verbose_name='日度价格')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.City', verbose_name='城市/区')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
            ],
            options={
                'verbose_name': '各地市区鸡蛋日度价格',
                'verbose_name_plural': '各地市区鸡蛋日度价格',
                'db_table': 'egg_dailypricedetail',
            },
        ),
        migrations.CreateModel(
            name='DailyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('p_daily_price', models.FloatField(blank=True, null=True, verbose_name='省均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '鸡蛋省级日均价',
                'verbose_name_plural': '鸡蛋省级日均价',
                'db_table': 'egg_dailypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='DailyPriceQGAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('daily_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('chan_dailyprice', models.FloatField(blank=True, null=True, verbose_name='主产区均价')),
                ('xiao_dailyprice', models.FloatField(blank=True, null=True, verbose_name='主销区均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
            ],
            options={
                'verbose_name': '鸡蛋全国日均价',
                'verbose_name_plural': '鸡蛋全国日均价',
                'db_table': 'egg_dailypriceqgavg',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='周度')),
                ('p_monthly_price', models.FloatField(blank=True, null=True, verbose_name='省均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '省级月度均价',
                'verbose_name_plural': '省级月度均价',
                'db_table': 'egg_monthlypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPriceQGAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('month_price', models.FloatField(blank=True, null=True, verbose_name='月价')),
                ('chan_monthlyprice', models.FloatField(blank=True, null=True, verbose_name='主产区均价')),
                ('xiao_monthlyprice', models.FloatField(blank=True, null=True, verbose_name='主销区均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
            ],
            options={
                'verbose_name': '鸡蛋全国月度价格均价',
                'verbose_name_plural': '鸡蛋全国月度价格均价',
                'db_table': 'egg_monthlypriceqgavg',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('weekNum', models.IntegerField(verbose_name='周度')),
                ('p_weekly_price', models.FloatField(blank=True, null=True, verbose_name='省均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '鸡蛋省级周度均价',
                'verbose_name_plural': '鸡蛋省级周度均价',
                'db_table': 'egg_weeklypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPriceQGAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('weekNum', models.IntegerField(verbose_name='周度')),
                ('weekly_price', models.FloatField(blank=True, null=True, verbose_name='周价')),
                ('chan_weeklyprice', models.FloatField(blank=True, null=True, verbose_name='主产区均价')),
                ('xiao_weeklyprice', models.FloatField(blank=True, null=True, verbose_name='主销区均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
            ],
            options={
                'verbose_name': '鸡蛋全国周度价格均价',
                'verbose_name_plural': '鸡蛋全国周度价格均价',
                'db_table': 'egg_weeklypriceqgavg',
            },
        ),
        migrations.RemoveField(
            model_name='dandailypricedetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dandailypriceprovince',
            name='province',
        ),
        migrations.DeleteModel(
            name='DanDailyPriceQGAvg',
        ),
        migrations.RemoveField(
            model_name='danmonthlypriceprovince',
            name='province',
        ),
        migrations.DeleteModel(
            name='DanMonthlyPriceQGAvg',
        ),
        migrations.RemoveField(
            model_name='danweeklypriceprovince',
            name='province',
        ),
        migrations.DeleteModel(
            name='DanWeeklyPriceQGAvg',
        ),
        migrations.RemoveField(
            model_name='taojidailypricedetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='taojidailypriceprovince',
            name='province',
        ),
        migrations.DeleteModel(
            name='TaojiDailyPriceQGAvg',
        ),
        migrations.RemoveField(
            model_name='taojimonthlypriceprovince',
            name='province',
        ),
        migrations.DeleteModel(
            name='TaojiMonthlyPriceQGAvg',
        ),
        migrations.RemoveField(
            model_name='taojiweeklypriceprovince',
            name='province',
        ),
        migrations.DeleteModel(
            name='TaojiWeeklyPriceQGAvg',
        ),
        migrations.DeleteModel(
            name='DanDailyPriceDetail',
        ),
        migrations.DeleteModel(
            name='DanDailyPriceProvince',
        ),
        migrations.DeleteModel(
            name='DanMonthlyPriceProvince',
        ),
        migrations.DeleteModel(
            name='DanWeeklyPriceProvince',
        ),
        migrations.DeleteModel(
            name='TaojiDailyPriceDetail',
        ),
        migrations.DeleteModel(
            name='TaojiDailyPriceProvince',
        ),
        migrations.DeleteModel(
            name='TaojiMonthlyPriceProvince',
        ),
        migrations.DeleteModel(
            name='TaojiWeeklyPriceProvince',
        ),
    ]
