# Generated by Django 2.0.3 on 2020-08-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0005_auto_20200829_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('p_daily_price', models.FloatField(blank=True, null=True, verbose_name='省均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.PriceType', verbose_name='价格类型')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '鸡蛋省级日均价',
                'verbose_name_plural': '鸡蛋省级日均价',
                'db_table': 'egg_dailypriceprovince',
            },
        ),
    ]
