# Generated by Django 2.0.3 on 2020-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0006_dailypriceprovince'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycunchulanoutput',
            name='chanliang_type',
            field=models.IntegerField(choices=[(1, '祖代蛋鸡存栏量（育成期、产蛋期）'), (2, '父母代种鸡-育成期平均存栏量'), (3, '父母代种鸡-产蛋期平均存栏量'), (4, '商品代蛋雏鸡一日龄销售量'), (5, '鸡蛋产量（高产配套系鸡蛋产量）')]),
        ),
    ]
