# Generated by Django 2.0.3 on 2020-09-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0007_auto_20200830_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoupoDailyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('doupolevel', models.IntegerField(choices=[(1, '普通豆粕'), (2, '高等豆粕')], verbose_name='豆粕等级')),
                ('daily_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('province', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='egg.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '豆粕各省份日均价',
                'verbose_name_plural': '豆粕各省份日均价',
                'db_table': 'pig_doupodailypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='DoupoDailyPriceQuanguoAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('doupo_level', models.IntegerField(choices=[(1, '普通豆粕'), (2, '高等豆粕')], verbose_name='豆粕等级')),
                ('daily_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕全国日均价',
                'verbose_name_plural': '豆粕全国日均价',
                'db_table': 'pig_doupodailypricequanguoavg',
            },
        ),
        migrations.AlterField(
            model_name='weeklycunchulanoutput',
            name='chanliang_type',
            field=models.IntegerField(choices=[(1, '祖代蛋鸡存栏量（育成期、产蛋期）'), (2, '父母代种鸡-育成期平均存栏量'), (3, '父母代种鸡-产蛋期平均存栏量'), (4, '父母代种鸡-总存栏量'), (5, '商品代蛋雏鸡销售量'), (6, '商品代蛋鸡育成期总存栏量'), (7, '商品代蛋鸡产蛋期总存栏量'), (8, '商品代蛋鸡总存栏量'), (9, '鸡蛋产量-总重量'), (10, '鸡蛋产量-总数量'), (11, '淘汰鸡总数量')]),
        ),
    ]
