# Generated by Django 2.0.3 on 2020-09-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0009_auto_20200904_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yumidailypriceprovince',
            name='province',
        ),
        migrations.DeleteModel(
            name='YumiDailyPriceQuanguoAvg',
        ),
        migrations.DeleteModel(
            name='YumiDailyPriceProvince',
        ),
    ]
