# Generated by Django 2.0.3 on 2020-09-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0010_auto_20200904_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyIntroducedMedian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('originYear', models.IntegerField(verbose_name='入舍年份')),
                ('originWeek', models.IntegerField(verbose_name='入舍周度')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('shengchanWeek', models.IntegerField(blank=True, default=1, null=True, verbose_name='生产周编号')),
                ('leijiProfit', models.FloatField(blank=True, null=True, verbose_name='累计利润')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
