# Generated by Django 2.0.3 on 2020-09-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0011_weeklyintroducedmedian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyintroducedmedian',
            old_name='WeekNum',
            new_name='weekNum',
        ),
        migrations.RenameField(
            model_name='weeklyintroducedmedian',
            old_name='Year',
            new_name='year',
        ),
    ]
