# Generated by Django 2.0.3 on 2020-09-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0012_auto_20200921_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyIntroducedMedian',
        ),
    ]
