# Generated by Django 2.0.3 on 2020-09-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0014_weeklyintroducedmedian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyIntroducedMedian',
            new_name='WeeklyDanjiLeijiProfit',
        ),
    ]
