# Generated by Django 2.0.3 on 2020-09-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0003_auto_20200904_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='YumiDailyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('yumipricetype', models.IntegerField(choices=[(1, '出库平仓价格'), (2, '深加工企业挂牌价'), (3, '饲料企业进厂价'), (4, '农户出售价'), (5, '玉米到货价')], verbose_name='玉米种类')),
                ('daily_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.ProvinceStandard', verbose_name='省份')),
            ],
            options={
                'verbose_name': '玉米各省份日均价',
                'verbose_name_plural': '玉米各省份日均价',
                'db_table': 'egg_yumidailypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='YumiDailyPriceQuanguoAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('yumipricetype', models.IntegerField(choices=[(1, '出库平仓价格'), (2, '深加工企业挂牌价'), (3, '饲料企业进厂价'), (4, '农户出售价'), (5, '玉米到货价')], verbose_name='玉米种类')),
                ('daily_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '玉米全国日均价',
                'verbose_name_plural': '玉米全国日均价',
                'db_table': 'egg_yumidailypricequanguoavg',
            },
        ),
    ]
