# Generated by Django 2.0.3 on 2020-09-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200904_2305'),
        ('yumi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YumiDailyPriceProvince',
            new_name='DailyPriceProvince',
        ),
        migrations.RenameModel(
            old_name='YumiDailyPriceQuanguoAvg',
            new_name='DailyPriceQuanguoAvg',
        ),
        migrations.AlterModelTable(
            name='dailypriceprovince',
            table='yumi_dailypriceprovince',
        ),
        migrations.AlterModelTable(
            name='dailypricequanguoavg',
            table='yumi_dailypricequanguoavg',
        ),
    ]
