# Generated by Django 2.0.3 on 2020-09-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200904_2305'),
        ('yumi', '0002_auto_20200904_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPriceQuanguoAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='几月')),
                ('monthly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '玉米全国月均价',
                'verbose_name_plural': '玉米全国月均价',
                'db_table': 'yumi_monthlypricequanguoavg',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPriceQuanguoAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('weekNum', models.IntegerField(verbose_name='第几周')),
                ('weekly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '玉米全国周均价',
                'verbose_name_plural': '玉米全国周均价',
                'db_table': 'yumi_weeklypricequanguoavg',
            },
        ),
        migrations.CreateModel(
            name='YumiDailyPriceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('dailyprice', models.FloatField(blank=True, null=True, verbose_name='日度价格')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('yumicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.City', verbose_name='城市/港口')),
            ],
            options={
                'verbose_name': '玉米各地区日度价格',
                'verbose_name_plural': '玉米各地区日度价格',
                'db_table': 'yumi_dailypricedetail',
            },
        ),
        migrations.CreateModel(
            name='YumiMonthlyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='几月')),
                ('monthly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '玉米各省份月均价',
                'verbose_name_plural': '玉米各省份月均价',
                'db_table': 'yumi_monthlypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='YumiPriceType',
            fields=[
                ('yumipricetype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('pricetypeName', models.CharField(max_length=16, verbose_name='价格分类名字')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='YumiWeeklyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('weekNum', models.IntegerField(verbose_name='第几周')),
                ('yumipricetype', models.IntegerField(choices=[(1, '出库平仓价格'), (2, '深加工企业挂牌价'), (3, '饲料企业进厂价'), (4, '农户出售价'), (5, '玉米到货价')], verbose_name='玉米种类')),
                ('weekly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '玉米各省份周均价',
                'verbose_name_plural': '玉米各省份周均价',
                'db_table': 'yumi_weeklypriceprovince',
            },
        ),
        migrations.AlterField(
            model_name='dailypriceprovince',
            name='yumipricetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumi.YumiPriceType', verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='dailypricequanguoavg',
            name='yumipricetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumi.YumiPriceType', verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='yumimonthlypriceprovince',
            name='yumipricetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yumi.YumiPriceType', verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='yumidailypricedetail',
            name='yumipricetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumi.YumiPriceType', verbose_name='玉米分类'),
        ),
        migrations.AddField(
            model_name='weeklypricequanguoavg',
            name='yumipricetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumi.YumiPriceType', verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='monthlypricequanguoavg',
            name='yumipricetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yumi.YumiPriceType', verbose_name='种类'),
        ),
    ]
