# Generated by Django 2.0.3 on 2020-09-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200904_2305'),
        ('yumi', '0004_auto_20200904_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyPriceProvince',
            new_name='YumiDailyPriceProvince',
        ),
        migrations.RenameModel(
            old_name='DailyPriceQuanguoAvg',
            new_name='YumiDailyPriceQuanguoAvg',
        ),
        migrations.RenameModel(
            old_name='MonthlyPriceQuanguoAvg',
            new_name='YumiMonthlyPriceQuanguoAvg',
        ),
        migrations.RenameModel(
            old_name='WeeklyPriceQuanguoAvg',
            new_name='YumiWeeklyPriceQuanguoAvg',
        ),
    ]
