# Generated by Django 2.0.3 on 2020-09-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aminotype',
            table='amino_producttype',
        ),
    ]
