# Generated by Django 2.0.3 on 2020-09-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amino', '0002_auto_20200905_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aminoweeklyprice',
            name='aminotype',
        ),
        migrations.DeleteModel(
            name='AminoWeeklyPrice',
        ),
    ]
