# Generated by Django 2.0.3 on 2020-09-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('cityName', models.CharField(max_length=16, verbose_name='城市')),
                ('danSalesAreaFlag', models.IntegerField(default=0, verbose_name='鸡蛋产区')),
                ('tSalesAreaFlag', models.IntegerField(default=0, verbose_name='淘汰鸡产区')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('provinceName', models.CharField(blank=True, max_length=16, null=True, verbose_name='省份')),
                ('cityContain', models.CharField(blank=True, max_length=16, null=True, verbose_name='包含城市')),
                ('danSalesAreaFlag', models.IntegerField(default=0, verbose_name='鸡蛋产区')),
                ('tSalesAreaFlag', models.IntegerField(default=0, verbose_name='淘汰鸡产区')),
                ('order', models.IntegerField(verbose_name='排序')),
                ('EnglishName', models.CharField(blank=True, max_length=32, null=True, verbose_name='英文名字')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Province', verbose_name='所属省份'),
        ),
    ]
