# Generated by Django 2.0.3 on 2020-09-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20200904_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Province',
            new_name='ProvinceStandard',
        ),
    ]
