# Generated by Django 2.0.3 on 2020-09-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumi', '0001_initial'),
        ('basic', '0003_auto_20200904_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProvinceStandard',
            new_name='Province',
        ),
    ]
