# Generated by Django 2.0.3 on 2020-09-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggFuturesPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('futureCode', models.IntegerField(verbose_name='期货')),
                ('eggFuturePrice', models.IntegerField(blank=True, null=True, verbose_name='期货价格')),
                ('isMainFlag', models.IntegerField(blank=True, null=True, verbose_name='是否是主力合约')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
