# Generated by Django 2.0.3 on 2020-09-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eggfuturesprice',
            options={'verbose_name': '期货价格', 'verbose_name_plural': '期货价格'},
        ),
        migrations.AlterModelTable(
            name='eggfuturesprice',
            table='futures_eggfuturesprice',
        ),
    ]
