# Generated by Django 2.0.3 on 2020-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0003_eggmainprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggmainprice',
            name='xianhuoPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='现货价格'),
        ),
    ]
