# Generated by Django 2.0.3 on 2020-09-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0004_eggmainprice_xianhuoprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EggMainPrice',
        ),
    ]
