# Generated by Django 2.0.3 on 2020-09-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0005_delete_eggmainprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggMainPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('eggFuturePrice', models.IntegerField(blank=True, null=True, verbose_name='期货价格')),
                ('xianhuoPrice', models.IntegerField(blank=True, null=True, verbose_name='现货价格')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
