# Generated by Django 2.0.3 on 2020-09-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0006_eggmainprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesCompany',
            fields=[
                ('futurescompany_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('companyName', models.CharField(blank=True, max_length=64, null=True, verbose_name='期货公司名称')),
                ('companyFullName', models.CharField(blank=True, max_length=64, null=True, verbose_name='期货公司全名')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
