# Generated by Django 2.0.3 on 2020-09-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0007_futurescompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuturesCompany',
        ),
    ]
