# Generated by Django 2.0.3 on 2020-09-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200904_2305'),
        ('futures', '0008_delete_futurescompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesCompany',
            fields=[
                ('futurescompany_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('companyName', models.CharField(blank=True, max_length=64, null=True, verbose_name='期货公司名称')),
                ('companyFullName', models.CharField(blank=True, max_length=64, null=True, verbose_name='期货公司全名')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Province', verbose_name='省份')),
            ],
        ),
    ]
