# Generated by Django 2.0.3 on 2020-09-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0010_chicanginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicanginfo',
            name='futurescompany',
        ),
        migrations.DeleteModel(
            name='ChicangInfo',
        ),
    ]
