# Generated by Django 2.0.3 on 2020-09-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VitaminMonthlyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='分月')),
                ('monthlyprice', models.FloatField(blank=True, null=True, verbose_name='月度价格')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'vitamin_monthlyprice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VitaminDailyPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('dailyprice', models.FloatField(blank=True, null=True, verbose_name='日度价格')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'vitamin_dailyprice',
            },
        ),
        migrations.CreateModel(
            name='VitaminType',
            fields=[
                ('vitamintype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('vitaminName', models.CharField(max_length=64, verbose_name='维生素类别')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '维生素类别',
                'verbose_name_plural': '维生素类别',
                'db_table': 'vitamin_producttype',
            },
        ),
        migrations.CreateModel(
            name='VitaminWeeklyPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('weeklyprice', models.FloatField(blank=True, null=True, verbose_name='周度价格')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('vitamintype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitamin.VitaminType', verbose_name='维生素类型')),
            ],
            options={
                'verbose_name': '维生素周度价格',
                'verbose_name_plural': '维生素周度价格',
                'db_table': 'vitamin_weeklyprice',
            },
        ),
        migrations.AddField(
            model_name='vitamindailyprice',
            name='vitamintype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitamin.VitaminType', verbose_name='维生素类型'),
        ),
    ]
