# Generated by Django 2.0.3 on 2020-09-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0002_auto_20200905_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitaminWeeklyPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('weekNum', models.IntegerField(verbose_name='周度')),
                ('weeklyprice', models.FloatField(blank=True, null=True, verbose_name='周度价格')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('vitamintype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitamin.VitaminType', verbose_name='维生素类型')),
            ],
            options={
                'verbose_name': '维生素周度价格',
                'verbose_name_plural': '维生素周度价格',
                'db_table': 'vitamin_weeklyprice',
            },
        ),
    ]
