# Generated by Django 2.0.3 on 2020-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0003_vitaminweeklyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamintype',
            name='danwei',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='vitamintype',
            name='dataFrom',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='数据来源'),
        ),
    ]
