# Generated by Django 2.0.3 on 2020-09-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0004_auto_20200904_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoupoDailyPriceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('dailyprice', models.FloatField(blank=True, null=True, verbose_name='日度价格')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('doupocity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.City', verbose_name='城市/港口')),
            ],
            options={
                'verbose_name': '豆粕各地区日度价格',
                'verbose_name_plural': '豆粕各地区日度价格',
                'db_table': 'doupo_dailypricedetail',
            },
        ),
        migrations.CreateModel(
            name='DoupoDailyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('daily_price', models.FloatField(blank=True, null=True, verbose_name='各省价格')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕各省份日均价',
                'verbose_name_plural': '豆粕各省份日均价',
                'db_table': 'doupo_dailypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='DoupoDailyPriceQuanguoAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(verbose_name='日期')),
                ('daily_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕全国日均价',
                'verbose_name_plural': '豆粕全国日均价',
                'db_table': 'doupo_dailypricequanguoavg',
            },
        ),
        migrations.CreateModel(
            name='DoupoMonthlyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='几月')),
                ('monthly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕各省份月均价',
                'verbose_name_plural': '豆粕各省份月均价',
                'db_table': 'doupo_monthlypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='DoupoMonthlyPriceQuanguoAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='几月')),
                ('monthly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕全国月均价',
                'verbose_name_plural': '豆粕全国月均价',
                'db_table': 'doupo_monthlypricequanguoavg',
            },
        ),
        migrations.CreateModel(
            name='DoupoWeeklyPriceProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('weekNum', models.IntegerField(verbose_name='第几周')),
                ('weekly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕各省份周均价',
                'verbose_name_plural': '豆粕各省份周均价',
                'db_table': 'doupo_weeklypriceprovince',
            },
        ),
        migrations.CreateModel(
            name='DoupoWeeklyPriceQuanguoAvg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('weekNum', models.IntegerField(verbose_name='第几周')),
                ('weekly_price', models.FloatField(blank=True, null=True, verbose_name='全国均价')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕全国周均价',
                'verbose_name_plural': '豆粕全国周均价',
                'db_table': 'doupo_weeklypricequanguoavg',
            },
        ),
        migrations.CreateModel(
            name='ProductLevel',
            fields=[
                ('doupolevel_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('levelName', models.CharField(max_length=16, verbose_name='等级')),
                ('comments', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '豆粕等级表',
                'verbose_name_plural': '豆粕等级表',
                'db_table': 'doupo_productlevel',
            },
        ),
        migrations.AddField(
            model_name='doupoweeklypricequanguoavg',
            name='doupolevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doupo.ProductLevel', verbose_name='豆粕等级'),
        ),
        migrations.AddField(
            model_name='doupoweeklypriceprovince',
            name='doupolevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doupo.ProductLevel', verbose_name='豆粕等级'),
        ),
        migrations.AddField(
            model_name='doupoweeklypriceprovince',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='doupomonthlypricequanguoavg',
            name='doupolevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doupo.ProductLevel', verbose_name='豆粕等级'),
        ),
        migrations.AddField(
            model_name='doupomonthlypriceprovince',
            name='doupolevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doupo.ProductLevel', verbose_name='豆粕等级'),
        ),
        migrations.AddField(
            model_name='doupomonthlypriceprovince',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='doupodailypricequanguoavg',
            name='doupolevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doupo.ProductLevel', verbose_name='豆粕等级'),
        ),
        migrations.AddField(
            model_name='doupodailypriceprovince',
            name='doupolevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doupo.ProductLevel', verbose_name='豆粕等级'),
        ),
        migrations.AddField(
            model_name='doupodailypriceprovince',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='doupodailypricedetail',
            name='doupolevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doupo.ProductLevel', verbose_name='豆粕等级'),
        ),
    ]
